# Generated by Django 5.2.13 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0002_uploadedfile_file_size_uploadedfile_file_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="risk_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="ai_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="ai_generated",
            field=models.BooleanField(default=False),
        ),
    ]

